name: Node CI

on: [push]

jobs:
  #  test:
  #    runs-on: ubuntu-latest
  #
  #    strategy:
  #      matrix:
  #        node-version: [14.x]
  #
  #    steps:
  #      - uses: actions/checkout@v2
  #      - name: Use Node.js ${{ matrix.node-version }}
  #        uses: actions/setup-node@v1
  #        with:
  #          node-version: ${{ matrix.node-version }}
  #      - run: yarn install --frozen-lockfile
  #      - run: yarn test

  deploy:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'
    #    needs: test

    steps:
      - name: Deploy
        uses: satak/webrequest-action@master
        with:
          url: https://andriaus.lt/api/deploy
          method: GET
